### ISSUE TITLE
kdf value is not set in README.md example

### ISSUE THREAD

**Issue by cryptofusion** [sunknudsen/blockcrypt#1]
I'm still exploring the code and trying to understand it. I think kdf is not set in the readme example. When compiling the example code locally, getting

`Cannot find name 'kdf'.`

coming from line 19:
`const block = await encrypt(secrets, kdf)`

**Comment by sunknudsen** [comment]
Hey, thanks so much for looking into the code and offering feedback.

Blockcrypt does not provide a key derivation function “by design” so developers can provide their own (for example, [Superbacked](https://superbacked.com/) uses [Argon2](https://github.com/P-H-C/phc-winner-argon2)).

For experimentation purposes (or unit tests), an insecure key derivation function is available [here](https://github.com/sunknudsen/blockcrypt/blob/master/src/test.ts#L20-L27).

Thanks again for helping out!
